# Lattice Makefile — the lifecycle, delegated.
#
# Every lifecycle target is exactly its `fluxor` verb, with no per-repo recipe
# body (../standards/make.md §2-3). The bodies are gate-enforced character for
# character by `fluxor ci`'s `makefile` phase: they can be identical across
# projects because the VERB is not — each reads this checkout's shape (no root
# `Cargo.toml`; `modules/` + `[ci].targets`; the `tests/harness` host crate via
# `[ci.cargo] host_tools_crate`; the `[ci.test]` scripts that fmt/clippy/build
# the standalone `tools/*` crates and run the wire_lint / telemetry_guard
# gates) and does what that shape implies. `make help` is generated by
# `fluxor help --make`, which walks `tools/` for real, so the printed list can
# never fall behind the tree.
#
# `shadow-status` / `shadow-log` are not lifecycle targets; §3 allows plain
# invocations in sequence. Shadow-tracked `tests/`, `benches/`, `examples/`,
# `perf/` (../standards/test-tracking.md) are invisible to `git status` on the
# primary, so read them alongside it. Staging NEW files needs `-f` plus the
# exclude pathspecs; see README.md.

.PHONY: help build test lint ci publish clean shadow-status shadow-log

SHELL       := /bin/bash
.SHELLFLAGS := -euo pipefail -c

.DEFAULT_GOAL := build

help:
	@fluxor help --make

build:
	fluxor build

test:
	fluxor test

lint:
	fluxor lint

ci:
	fluxor ci

publish:
	fluxor publish

clean:
	fluxor clean

shadow-status: ; git shadow status
shadow-log:    ; git shadow log --oneline -20
